# Alertmanager Configuration for SmartCompute
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@smartcompute.local'
  smtp_auth_username: 'alerts@smartcompute.local'
  smtp_auth_password: 'alert_password_from_vault'

# Inhibition rules
inhibit_rules:
  # Inhibit critical alerts if service is down
  - source_match:
      severity: 'critical'
      alertname: 'ServiceDown'
    target_match:
      service: 'same'
    equal: ['service', 'instance']

  # Inhibit warning alerts if critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'instance']

# Routing configuration
route:
  group_by: ['service', 'alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: 'critical'
      receiver: 'critical-alerts'
      group_wait: 10s
      repeat_interval: 30m
      
    # Security alerts - immediate notification
    - match_re:
        alertname: '.*Threat.*|.*Security.*|.*Authentication.*'
      receiver: 'security-team'
      group_wait: 10s
      repeat_interval: 1h
      
    # Payment alerts - business team
    - match:
        service: 'payment'
      receiver: 'business-team'
      group_wait: 1m
      repeat_interval: 1h
      
    # Infrastructure alerts
    - match_re:
        alertname: '.*Database.*|.*Redis.*|.*Vault.*|.*CPU.*|.*Memory.*'
      receiver: 'infrastructure-team'
      group_wait: 2m
      repeat_interval: 2h

# Notification receivers
receivers:
  # Default receiver
  - name: 'default-receiver'
    email_configs:
      - to: 'alerts@smartcompute.local'
        subject: '[SmartCompute] Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}
        headers:
          X-Priority: 'Normal'

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'critical-alerts@smartcompute.local,admin@smartcompute.local'
        subject: '[CRITICAL] SmartCompute Alert: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          
          Runbook: https://docs.smartcompute.local/runbooks/{{ .Labels.alertname }}
          {{ end }}
        headers:
          X-Priority: 'High'
          
    # Webhook for integrations (Slack, PagerDuty, etc.)
    webhook_configs:
      - url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        send_resolved: true
        title: 'SmartCompute Critical Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # Security team notifications
  - name: 'security-team'
    email_configs:
      - to: 'security@smartcompute.local'
        subject: '[SECURITY] SmartCompute Security Alert'
        body: |
          🛡️ SECURITY ALERT 🛡️
          
          {{ range .Alerts }}
          Security Event: {{ .Annotations.summary }}
          Details: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Threat Level: {{ .Labels.severity }}
          Detection Time: {{ .StartsAt }}
          
          Please investigate immediately.
          {{ end }}
        headers:
          X-Priority: 'High'

  # Business team for payment/revenue alerts
  - name: 'business-team'
    email_configs:
      - to: 'business@smartcompute.local,finance@smartcompute.local'
        subject: '[BUSINESS] SmartCompute Business Metric Alert'
        body: |
          📊 BUSINESS ALERT 📊
          
          {{ range .Alerts }}
          Business Alert: {{ .Annotations.summary }}
          Impact: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Priority: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}
        headers:
          X-Priority: 'Normal'

  # Infrastructure team
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@smartcompute.local,devops@smartcompute.local'
        subject: '[INFRA] SmartCompute Infrastructure Alert'
        body: |
          ⚙️ INFRASTRUCTURE ALERT ⚙️
          
          {{ range .Alerts }}
          Infrastructure Issue: {{ .Annotations.summary }}
          Details: {{ .Annotations.description }}
          Component: {{ .Labels.service }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          
          Dashboard: https://grafana.smartcompute.local/d/infrastructure/infrastructure-overview
          {{ end }}
        headers:
          X-Priority: 'Normal'