"""Initial migration - create all tables

Revision ID: 757483abc46f
Revises: 
Create Date: 2025-08-25 21:32:07.804688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757483abc46f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_profile_id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('cpu_zscore', sa.Float(), nullable=False),
    sa.Column('memory_zscore', sa.Float(), nullable=False),
    sa.Column('additional_metrics', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('alert_generated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_detections_id'), 'anomaly_detections', ['id'], unique=False)
    op.create_table('computation_optimizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_profile_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('operation_key', sa.String(length=200), nullable=False),
    sa.Column('precision_required', sa.Float(), nullable=False),
    sa.Column('speed_priority', sa.Float(), nullable=False),
    sa.Column('chosen_method', sa.String(length=50), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('accuracy_achieved', sa.Float(), nullable=False),
    sa.Column('speedup_factor', sa.Float(), nullable=False),
    sa.Column('meets_precision', sa.Boolean(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computation_optimizations_id'), 'computation_optimizations', ['id'], unique=False)
    op.create_table('monitoring_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_profile_id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('check_interval', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('total_alerts', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_sessions_id'), 'monitoring_sessions', ['id'], unique=False)
    op.create_table('optimization_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_profile_id', sa.Integer(), nullable=False),
    sa.Column('operation_key', sa.String(length=200), nullable=False),
    sa.Column('precise_time', sa.Float(), nullable=False),
    sa.Column('fast_time', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('speedup', sa.Float(), nullable=False),
    sa.Column('chosen_method', sa.String(length=50), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_history_id'), 'optimization_history', ['id'], unique=False)
    op.create_table('performance_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_profile_id', sa.Integer(), nullable=False),
    sa.Column('baseline_name', sa.String(length=100), nullable=False),
    sa.Column('cpu_mean', sa.Float(), nullable=False),
    sa.Column('cpu_stdev', sa.Float(), nullable=False),
    sa.Column('memory_mean', sa.Float(), nullable=False),
    sa.Column('memory_stdev', sa.Float(), nullable=False),
    sa.Column('measurement_duration', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_baselines_id'), 'performance_baselines', ['id'], unique=False)
    op.create_table('performance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_profile_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_reports_id'), 'performance_reports', ['id'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitoring_session_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_detection_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_id'), 'security_alerts', ['id'], unique=False)
    op.create_table('system_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=True),
    sa.Column('os_name', sa.String(length=50), nullable=False),
    sa.Column('architecture', sa.String(length=50), nullable=False),
    sa.Column('cpu_model', sa.String(length=200), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('cpu_threads', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Float(), nullable=False),
    sa.Column('gpu_type', sa.String(length=100), nullable=False),
    sa.Column('gpu_available', sa.Boolean(), nullable=True),
    sa.Column('cuda_available', sa.Boolean(), nullable=True),
    sa.Column('opencl_available', sa.Boolean(), nullable=True),
    sa.Column('optimization_strategy', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_profiles_id'), 'system_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_system_profiles_profile_name'), 'system_profiles', ['profile_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_profiles_profile_name'), table_name='system_profiles')
    op.drop_index(op.f('ix_system_profiles_id'), table_name='system_profiles')
    op.drop_table('system_profiles')
    op.drop_index(op.f('ix_security_alerts_id'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_performance_reports_id'), table_name='performance_reports')
    op.drop_table('performance_reports')
    op.drop_index(op.f('ix_performance_baselines_id'), table_name='performance_baselines')
    op.drop_table('performance_baselines')
    op.drop_index(op.f('ix_optimization_history_id'), table_name='optimization_history')
    op.drop_table('optimization_history')
    op.drop_index(op.f('ix_monitoring_sessions_id'), table_name='monitoring_sessions')
    op.drop_table('monitoring_sessions')
    op.drop_index(op.f('ix_computation_optimizations_id'), table_name='computation_optimizations')
    op.drop_table('computation_optimizations')
    op.drop_index(op.f('ix_anomaly_detections_id'), table_name='anomaly_detections')
    op.drop_table('anomaly_detections')
    # ### end Alembic commands ###
