# Grafana Datasources Configuration
apiVersion: 1

datasources:
  # Prometheus - Main metrics source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: false
      alertmanagerUid: alertmanager
    version: 1

  # Alertmanager - Alerts
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    uid: alertmanager
    jsonData:
      implementation: prometheus
    version: 1

  # PostgreSQL - Direct database access for logs/audit queries
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: smartcompute-postgres:5432
    database: smartcompute
    user: smartcompute
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    version: 1